# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: cache sonar cloud packages
      uses: actions/cache@v2.1.3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: test project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
